server:
  port: 8080

spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379

# Actuator 보안 설정 샘플

# 1. Endpoint all disable
management:
  health:
    redis:
      enabled: false
  endpoint:
    health:
      show-details: always
  info:
    java:
      enabled: true
    env:
      enabled: true
    build:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info, health
    jmx:
      exposure:
        exclude: '*'
